### ISSUE TITLE
rotation doesn't work properly

### ISSUE THREAD

**Issue by tarockx** [haiiaaa/chartjs-gauge#1]
Hello, and thanks for this plugin, it's great.

I just wanted to report that rotation seems not to be working properly. If you set a rotation in the options different from the default one, for example:

```
options: {
        rotation: Math.PI * -0.5,
        ...
}
```

the needle is improperly placed, like in this screenshot:
![image](https://user-images.githubusercontent.com/10919460/73274010-25759300-41e5-11ea-974c-2bb96589b91f.png)

Would it possible to fix this?
Thanks again for your work.

**Comment by haiiaaa** [comment]
Rotation should work now.
