### ISSUE TITLE
Set Range

### ISSUE THREAD

**Issue by klienn** [haiiaaa/chartjs-gauge#13]
I wanted to start my chart at negative values and I can't find any solution online, how can I achieve this?

**Comment by haiiaaa** [comment]
Are you talking about rotation?

**Comment by klienn** [comment]
@haiiaaa no, i want the starting value to be negative. Whenever I tried to use a negative value, the pointer goes beyond the starting bar

**Comment by haiiaaa** [comment]
How would you represent a negative value in a pie/doughnut chart? 
Try to a negative value in the example editors https://www.chartjs.org/docs/master/charts/doughnut/

**Comment by haiiaaa** [comment]
I think know what you mean now, so I will fix this.

**Comment by haiiaaa** [comment]
Fixed in version 0.3.0, duplicate of #18
