### ISSUE TITLE
Extension doesn't work at ChartJs version 3.2.1.

### ISSUE THREAD

**Issue by Squizelland** [haiiaaa/chartjs-gauge#19]
I was trying to use the ChartJs version 3.2.1, but suddenly the gauge doesn't appear. But if i use the 2.9.0 version is still good. Has anyone got the same issue here? Thanks before.

**Comment by jbsgh** [comment]
Duplicate of #14

ChartJs 3 and ChartJs 2 are not compatible.

**Comment by haiiaaa** [comment]
Duplicate of #14
