### ISSUE TITLE
TextHeight calculation can be improved

### ISSUE THREAD

**Issue by av01d** [haiiaaa/chartjs-gauge#4]
Line 243 of chartjs-gauge.js measures text height like this:
```
var textHeight = ctx.measureText('M').width;
```

This works fine for some fonts, but not so much for other (f.e. Google) fonts. A better method is:
```
var textHeight = Math.max(ctx.measureText('m').width, ctx.measureText('\uFF37').width);
```

Now you need to change the default padding to:
```
padding: { top: 5, right: 5, bottom: 10, left: 5 }
```

In my tests (I tested with a LOT of Google fonts), these small changes result in a much better design for the needle-value-box.

**Comment by haiiaaa** [comment]
Thanks! Try version 0.1.2

**Comment by av01d** [comment]
Perfect, looks much better. Thank you!
