### ISSUE TITLE
Online examples

### ISSUE THREAD

**Issue by atleta** [haiiaaa/chartjs-gauge#7]
Hi,

Have you thought about publishing the examples online (practically as github pages), so that one could look at it without cloning the repo and then building it? (And/or adding screenhots to the readme and/or adding a to a jsfiddle containing the code from the example in the readme.)

**Comment by haiiaaa** [comment]
What about these? https://github.com/haiiaaa/chartjs-gauge#samples

**Comment by muhghazaliakbar** [comment]
> What about these? https://github.com/haiiaaa/chartjs-gauge#samples

@atleta This is your answer.
